config/routes.rb
Rails.application.routes.draw do
  root 'houses#index'

  resources :energies, only: %i[index] do
    collection { post :import}
  end

  resources :houses, only: %i[index show] do
    collection { post :import}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/energy.rb
class Energy < ApplicationRecord
  UPDATABLE_ATTRIBUTES = %w[id label house_id year month temperature daylight energy_production]
  belongs_to :house

  scope :chart_by_year_filter_house, -> (year, id) {where(house: id, year: year).group(:month)}
  scope :chart_by_year_filter_city, -> (year, id) {joins(:house).where(houses: {city: House.find(id).city}, year: year).group(:month)}

  def self.years
    self.all.group(:year).pluck(:year).sort
  end

  def self.chart_energies_production(id)
    years.map {|year| [year, self.chart_by_year_filter_house(year, id).sum(:energy_production)]}.to_h
  end

  def self.chart_energies_average(id)
    years.map {|year| [year, self.chart_by_year_filter_city(year, id).average(:energy_production)]}.to_h
  end

  def self.chart_daylight(id)
    years.map {|year| [year, chart_by_year_filter_city(year, id).average(:daylight)]}.to_h
  end

  def self.import(file)
    transaction do
      CSV.foreach(file.path,
                  headers: true,
                  header_converters: ->(h) {h.try(:downcase).try(:gsub, 'house', 'house_id').try(:gsub, 'energy', 'energy_')}
      ) do |row|
        energy = find_by(id: row["id"]) || new
        energy.attributes = row.to_hash.slice(*UPDATABLE_ATTRIBUTES)
        energy.save!
      end
    end
  end
end

app/models/house.rb
class House < ApplicationRecord
  has_many :energies

  def self.import(file)
    CSV.foreach(file.path,
                headers: true,
                header_converters: ->(h) {h.try(:downcase)}
    ) do |row|
      house = find_by(id: row["id"]) || new
      house.attributes = row.to_hash.slice(*updatable_attributes)
      house.save!
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "firstname", "lastname", "city", "num_of_people", "has_child"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/energies_controller.rb
class EnergiesController < ApplicationController
  def index
    @energies = Energy.all
  end

  def import
    Energy.import(params[:file])
    redirect_to energies_path
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %(show)
  def index
    @houses = House.all
  end

  def show
    years = Energy.years
    @chart_energies = Energy.chart_energies_production(params[:id])
    @chart_energies_avg = Energy.chart_energies_average(params[:id])
    @chart_daylights = Energy.chart_daylight(params[:id])
  end

  def import
    House.import(params[:file])
    redirect_to energy_houses_path
  end

  private

  def set_house
    @house = House.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/energies_helper.rb
module EnergiesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/energies/index.html.slim
h1 エネルギー生産量の一覧
= link_to "住居一覧", houses_path
hr
h5 エネルギー生産量データを追加する
= form_tag import_energies_path, multipart: true do
  = file_field_tag :file
  = submit_tag "インポート"
hr
br
table border="1"
  thead
    tr
      th 家のID
      th 年
      th 月
      th 気温
      th 日射量
      th エネルギー生産量
  tbody
    - @energies.each do |energy|
      tr
        td = energy.house_id
        td = energy.year
        td = energy.month
        td = energy.temperature
        td = energy.daylight
        td = energy.energy_production

app/views/houses/index.html.slim
h1 住居の一覧
= link_to "エネルギー生産量一覧", energies_path
hr
h5 住居を追加する
= form_tag import_houses_path, multipart: true do
  = file_field_tag :file
  = submit_tag "インポート"
hr
br
table border="1"
  thead
    tr
      th 名前
      th 性
      th 都市
      th 人数
      th 子供の有無
      th 詳細
  tbody
    - @houses.each do |house|
      tr
        td = house.firstname
        td = house.lastname
        td = house.city
        td = house.num_of_people
        td = house.has_child
        td = link_to "グラフを見る", house_path(house)

app/views/houses/show.html.slim
h1 #{@house.firstname}家の発電状況
hr
= link_to "住居一覧に戻る", houses_path
- @chart_energies.each do |key, value|
  h2 #{key}の月別合計値
  = line_chart [{name: "#{@house.firstname}家のエネルギー生産量", data: value},
          {name: "#{@house.city}の平均エネルギー生産量", data: @chart_energies_avg[key]},
          {name: "#{@house.city}の平均日射量", data: @chart_daylights[key]}]
br
table border="1"
  thead
    tr
      th 名前
      th 性
      th 都市
      th 人数
      th 子供の有無
  tbody
    tr
    td = @house.firstname
    td = @house.lastname
    td = @house.city
    td = @house.num_of_people
    td = @house.has_child

app/views/layouts/application.html.slim
doctype html
html
  head
    title Challenge3/RentoHitaka
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = yield